update idea builds and releases

diff --git a/idea/gear/squid/Dockerfile b/idea/gear/squid/Dockerfile
--- a/idea/gear/squid/Dockerfile
+++ b/idea/gear/squid/Dockerfile
@@ -1,18 +1,35 @@
-FROM node:20-alpine
+FROM node:20-alpine AS builder
 
 WORKDIR /src
+
+COPY . .
+
+# TODO: This command exited with non-zero code inside Docker container.
+# But with echo $? it returned 0. Need to investigate.
+RUN yarn workspaces focus @gear-js/api gear-idea-squid gear-idea-indexer-db gear-js; echo $?
+RUN yarn build:gear-idea-squid
+
+FROM node:20-alpine AS deps
+WORKDIR /deps
+
 COPY package.json .
 COPY yarn.lock .
-COPY tsconfig.json .
 COPY .yarn .yarn
 COPY .yarnrc.yml .
-COPY gear-js.sh .
-COPY ./idea/indexer-db idea/indexer-db
-COPY ./idea/squid idea/squid
-RUN chmod +x /src/gear-js.sh
+COPY apis/gear/package.json apis/gear/package.json
+COPY idea/gear/squid/package.json idea/gear/squid/package.json
+COPY idea/gear/indexer-db/package.json idea/gear/indexer-db/package.json
 
-RUN yarn install
-RUN ./gear-js.sh build indexer-db
-RUN ./gear-js.sh build squid
+RUN yarn workspaces focus --production
 
-CMD ["/bin/sh", "-c", "/src/gear-js.sh run squid"]
+FROM node:20-alpine
+
+COPY --from=deps /deps /src
+COPY --from=builder /src/apis/gear/lib /src/apis/gear/lib
+COPY --from=builder /src/idea/gear/squid/lib /src/idea/gear/squid/lib
+COPY --from=builder /src/idea/gear/indexer-db/lib /src/idea/gear/indexer-db/lib
+
+WORKDIR /src/idea/gear/squid
+
+
+CMD ["yarn", "run-with-migrations"]
